apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: licensingservice
  name: licensingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: licensingservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/docker_backend: "true"
        io.kompose.service: licensingservice
    spec:
      containers:
      - env:
        - name: CONFIGSERVER_PORT
          value: "8071"
        - name: CONFIGSERVER_URI
          value: http://configserver:8071
        - name: DATABASESERVER_PORT
          value: "5432"
        - name: ENCRYPT_KEY
          value: IMSYMMETRIC
        - name: PROFILE
          value: dev
        image: 758417428849.dkr.ecr.ap-northeast-2.amazonaws.com/ostock/licensing-service:chapter12
        imagePullPolicy: ""
        name: licensing-service
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
